 const LocationData ={"items": [
    {
        "locationID": "2c4d9dc1-1a08-42b4-87ff-0027a5fd3d1e",
        "internalLocationID": "646",
        "location": "646-Highland Memory Gardens",
        "address1": "279 Landis Ln. Mt.",
        "address2": null,
        "city": "Washington",
        "state": "KY",
        "postalCode": "40047",
        "country": "USA",
        "isActive": true,
        "addedBy": "perrychapman@zudy.com",
        "addedOn": "2022-09-09T18:09:05",
        "changedBy": "perrychapman@zudy.com",
        "changedOn": "2022-09-09T18:13:43.927",
        "locationTypeID": "cfe0c515-51f4-4b24-bf0a-152ed90f7081",
        "isStoneMor": true,
        "clusterID": "849a1d93-29e4-4c1f-b3b5-4f19880f9101",
        "locationPhone": null,
        "locationEmail": null,
        "defaultGPLNote": null,
        "sIMSID": 299,
        "gPLSummaryTitle": null,
        "isShowGPLSummary": false,
        "isGPLWatermarkDisplay": false,
        "isGlobalGPLNoteDisplay": true
    },
    {
        "locationID": "ad084b28-308c-11ed-9c4c-005056aa497d",
        "internalLocationID": "002",
        "location": "002-Marable Funeral Home ",
        "address1": null,
        "address2": null,
        "city": null,
        "state": null,
        "postalCode": null,
        "country": null,
        "isActive": false,
        "addedBy": null,
        "addedOn": null,
        "changedBy": "Vliza@stonemor.com",
        "changedOn": "2022-09-12T15:20:49.357",
        "locationTypeID": null,
        "isStoneMor": false,
        "clusterID": null,
        "locationPhone": null,
        "locationEmail": null,
        "defaultGPLNote": null,
        "sIMSID": 497,
        "gPLSummaryTitle": null,
        "isShowGPLSummary": false,
        "isGPLWatermarkDisplay": false,
        "isGlobalGPLNoteDisplay": true
    },
    {
        "locationID": "ad084b42-308c-11ed-9c4c-005056aa497d",
        "internalLocationID": "777",
        "location": "777-Test",
        "address1": null,
        "address2": null,
        "city": null,
        "state": null,
        "postalCode": null,
        "country": null,
        "isActive": true,
        "addedBy": null,
        "addedOn": null,
        "changedBy": null,
        "changedOn": null,
        "locationTypeID": null,
        "isStoneMor": true,
        "clusterID": null,
        "locationPhone": null,
        "locationEmail": null,
        "defaultGPLNote": null,
        "sIMSID": 499,
        "gPLSummaryTitle": null,
        "isShowGPLSummary": false,
        "isGPLWatermarkDisplay": false,
        "isGlobalGPLNoteDisplay": true
    },
    {
        "locationID": "ad084b4e-308c-11ed-9c4c-005056aa497d",
        "internalLocationID": "003",
        "location": "003-Marable Funeral Home ",
        "address1": null,
        "address2": null,
        "city": null,
        "state": null,
        "postalCode": null,
        "country": null,
        "isActive": false,
        "addedBy": null,
        "addedOn": null,
        "changedBy": "Vliza@stonemor.com",
        "changedOn": "2022-09-12T15:20:54.793",
        "locationTypeID": null,
        "isStoneMor": false,
        "clusterID": null,
        "locationPhone": null,
        "locationEmail": null,
        "defaultGPLNote": null,
        "sIMSID": 501,
        "gPLSummaryTitle": null,
        "isShowGPLSummary": false,
        "isGPLWatermarkDisplay": false,
        "isGlobalGPLNoteDisplay": true
    },
    {
        "locationID": "ad084b74-308c-11ed-9c4c-005056aa497d",
        "internalLocationID": "004",
        "location": "004-Smith Funeral Homes",
        "address1": null,
        "address2": null,
        "city": null,
        "state": null,
        "postalCode": null,
        "country": null,
        "isActive": false,
        "addedBy": null,
        "addedOn": null,
        "changedBy": "Vliza@stonemor.com",
        "changedOn": "2022-09-12T15:20:55.323",
        "locationTypeID": null,
        "isStoneMor": false,
        "clusterID": null,
        "locationPhone": null,
        "locationEmail": null,
        "defaultGPLNote": null,
        "sIMSID": 504,
        "gPLSummaryTitle": null,
        "isShowGPLSummary": false,
        "isGPLWatermarkDisplay": false,
        "isGlobalGPLNoteDisplay": true
    },
    {
        "locationID": "ad084b83-308c-11ed-9c4c-005056aa497d",
        "internalLocationID": "005",
        "location": "005-whateva",
        "address1": "wdawd 1231 st",
        "address2": "",
        "city": "Miami",
        "state": "FL",
        "postalCode": "33186",
        "country": null,
        "isActive": false,
        "addedBy": null,
        "addedOn": null,
        "changedBy": "Vliza@stonemor.com",
        "changedOn": "2022-09-12T15:20:55.95",
        "locationTypeID": null,
        "isStoneMor": false,
        "clusterID": null,
        "locationPhone": "1231231231",
        "locationEmail": null,
        "defaultGPLNote": null,
        "sIMSID": 506,
        "gPLSummaryTitle": null,
        "isShowGPLSummary": false,
        "isGPLWatermarkDisplay": false,
        "isGlobalGPLNoteDisplay": true
    },
    {
        "locationID": "ad084b93-308c-11ed-9c4c-005056aa497d",
        "internalLocationID": "007",
        "location": "007-test",
        "address1": null,
        "address2": null,
        "city": null,
        "state": null,
        "postalCode": null,
        "country": null,
        "isActive": false,
        "addedBy": null,
        "addedOn": null,
        "changedBy": "santinotorretti@zudy.com",
        "changedOn": "2022-10-05T10:13:27.453",
        "locationTypeID": null,
        "isStoneMor": false,
        "clusterID": null,
        "locationPhone": null,
        "locationEmail": null,
        "defaultGPLNote": null,
        "sIMSID": 507,
        "gPLSummaryTitle": null,
        "isShowGPLSummary": false,
        "isGPLWatermarkDisplay": false,
        "isGlobalGPLNoteDisplay": true
    },
    {
        "locationID": "ad084bb3-308c-11ed-9c4c-005056aa497d",
        "internalLocationID": "999",
        "location": "999-test",
        "address1": null,
        "address2": null,
        "city": null,
        "state": null,
        "postalCode": null,
        "country": null,
        "isActive": true,
        "addedBy": null,
        "addedOn": null,
        "changedBy": null,
        "changedOn": null,
        "locationTypeID": null,
        "isStoneMor": true,
        "clusterID": null,
        "locationPhone": null,
        "locationEmail": null,
        "defaultGPLNote": null,
        "sIMSID": 509,
        "gPLSummaryTitle": null,
        "isShowGPLSummary": false,
        "isGPLWatermarkDisplay": false,
        "isGlobalGPLNoteDisplay": true
    },
    {
        "locationID": "ad084ae0-308c-11ed-9c4c-005056aa497d",
        "internalLocationID": "555",
        "location": "Forest Lawn Cemetery",
        "address1": null,
        "address2": null,
        "city": null,
        "state": null,
        "postalCode": null,
        "country": null,
        "isActive": true,
        "addedBy": null,
        "addedOn": null,
        "changedBy": null,
        "changedOn": null,
        "locationTypeID": null,
        "isStoneMor": true,
        "clusterID": null,
        "locationPhone": null,
        "locationEmail": null,
        "defaultGPLNote": null,
        "sIMSID": 492,
        "gPLSummaryTitle": null,
        "isShowGPLSummary": false,
        "isGPLWatermarkDisplay": false,
        "isGlobalGPLNoteDisplay": true
    },
    {
        "locationID": "ace360e8-694c-4d6c-a29a-00b9b4872f2f",
        "internalLocationID": "604",
        "location": "604-Crown Hill Cemetery",
        "address1": "8592 Darrow Road",
        "address2": null,
        "city": "Twinsburg",
        "state": "OH",
        "postalCode": "44087",
        "country": "USA",
        "isActive": true,
        "addedBy": "perrychapman@zudy.com",
        "addedOn": "2022-09-09T18:09:05",
        "changedBy": "perrychapman@zudy.com",
        "changedOn": "2022-09-09T18:13:43.57",
        "locationTypeID": "cfe0c515-51f4-4b24-bf0a-152ed90f7081",
        "isStoneMor": true,
        "clusterID": "4b9bab07-d633-4960-95b6-ed3a0e57af9f",
        "locationPhone": null,
        "locationEmail": null,
        "defaultGPLNote": null,
        "sIMSID": 259,
        "gPLSummaryTitle": null,
        "isShowGPLSummary": false,
        "isGPLWatermarkDisplay": false,
        "isGlobalGPLNoteDisplay": true
    }
],}

export default LocationData;